version: 0.2

env:
  variables:
    ECR_URI: 492664494095.dkr.ecr.us-east-2.amazonaws.com
    REGION: us-east-2
    DOCKER_USERNAME: asaelsolorio
    DOCKER_PASSWORD: Solorio788@13

phases:
  pre_build:
    commands:
      - set -e
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

  build:
    commands:
      - set -e
      - echo Building consumer image...
      - docker build --platform linux/amd64 -t weather-consumer -f cmd/weather_consumer/Containerfile .
      - docker tag weather-consumer:latest $ECR_URI/consumer:$CODEBUILD_BUILD_NUMBER

      - echo Building ml-forecast image...
      - docker build --platform linux/amd64 -t ml-forecast -f pkg/mlforecast/Containerfile .
      - docker tag ml-forecast:latest $ECR_URI/ml-forecast:$CODEBUILD_BUILD_NUMBER

      - echo Building ui-service image...
      - docker build --platform linux/amd64 -t ui-service -f cmd/UI/Containerfile .
      - docker tag ui-service:latest $ECR_URI/ui-service:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - set -e
      - echo Pushing images to ECR...
      - docker push $ECR_URI/consumer:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_URI/ml-forecast:$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_URI/ui-service:$CODEBUILD_BUILD_NUMBER

      - echo Writing image details file...
      - printf '{"consumer":"%s","ml-forecast":"%s","ui-service":"%s"}' \
        $ECR_URI/consumer:$CODEBUILD_BUILD_NUMBER \
        $ECR_URI/ml-forecast:$CODEBUILD_BUILD_NUMBER \
        $ECR_URI/ui-service:$CODEBUILD_BUILD_NUMBER > imageDetails.json

artifacts:
  files:
    - imageDetails.json
  name: artifacts/imageDetails.json

cache:
  paths:
    - '/root/.cache/*'
