version: "3.9"

networks:
  weather-app-network:
    driver: bridge

services:
  forecaster-service:
    image: forecaster-service
    build:
      context: .
      dockerfile: pkg/mlforecast/Containerfile
    env_file:
      - .env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - weather-app-network

  ui-service:
    image: ui-service
    depends_on:
      - forecaster-service
    build:
      context: .
      dockerfile: cmd/UI/Containerfile
    ports:
      - "8000:8000"
    networks:
      - weather-app-network
    environment:
      WAIT_HOSTS: forecaster-service:5000
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 10
    command: ["sh", "-c", "/wait && ./ui"]

  weather-consumer:
    image: weather-consumer
    build:
      context: .
      dockerfile: cmd/weather_consumer/Containerfile
    ports:
      - "8080:8080"
    networks:
      - weather-app-network
